/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tripper;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MasterPage extends javax.swing.JFrame {

    /**
     * Creates new form LoadingSplash
     *
     * @throws java.sql.SQLException
     */
    public MasterPage() throws SQLException {
        initComponents();
        con = Tripper.getKoneksi();
        stat = con.createStatement();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 80, 80));
        LogoutHover.setVisible(false);
        harga.setText("Rp. ");
        initPaket();
        Notif_Ada.setVisible(false);
        Notif_Kosong.setVisible(false);
        Notif_Berhasil.setVisible(false);
        TambahHover.setVisible(false);
        UbahHover.setVisible(false);
        HapusHover.setVisible(false);
    }

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    public void initPaket() throws SQLException {

        cbox.removeAllItems();
        sql = "SELECT * FROM db_paket WHERE 1";
        rs = stat.executeQuery(sql);
        while (rs.next()) {
            cbox.addItem(rs.getString("KodePaket"));
        }
    }

    public void setSelected() throws SQLException {
        sql = "SELECT * FROM db_paket WHERE KodePaket='" + cbox.getSelectedItem() + "'";
        rs = stat.executeQuery(sql);
        while (rs.next()) {
            kodePaket.setText(rs.getString("KodePaket"));
            namaPaket.setText(rs.getString("NamaPaket"));
            harga.setText("Rp. " + rs.getString("Harga"));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadingSplash = new javax.swing.JPanel();
        MiniButton = new javax.swing.JLabel();
        CloseButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        Notif_Ada = new javax.swing.JLabel();
        Notif_Kosong = new javax.swing.JLabel();
        Notif_Berhasil = new javax.swing.JLabel();
        cbox = new javax.swing.JComboBox<>();
        kodePaket = new javax.swing.JTextField();
        namaPaket = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        HapusHover = new javax.swing.JLabel();
        Hapus = new javax.swing.JLabel();
        UbahHover = new javax.swing.JLabel();
        Ubah = new javax.swing.JLabel();
        TambahHover = new javax.swing.JLabel();
        Tambah = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        LogoutHover = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 844));
        setUndecorated(true);

        LoadingSplash.setMaximumSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setMinimumSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setPreferredSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setLayout(null);

        MiniButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MiniButton.png"))); // NOI18N
        MiniButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniButtonMouseClicked(evt);
            }
        });
        LoadingSplash.add(MiniButton);
        MiniButton.setBounds(340, 20, 33, 33);

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CloseButton.png"))); // NOI18N
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });
        LoadingSplash.add(CloseButton);
        CloseButton.setBounds(380, 20, 33, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot_199.png"))); // NOI18N
        LoadingSplash.add(jLabel1);
        jLabel1.setBounds(250, 140, 41, 40);

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        LoadingSplash.add(refresh);
        refresh.setBounds(390, 240, 27, 27);

        Notif_Ada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/master_pakai.png"))); // NOI18N
        LoadingSplash.add(Notif_Ada);
        Notif_Ada.setBounds(86, 475, 256, 20);

        Notif_Kosong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login_NotifKosong.png"))); // NOI18N
        LoadingSplash.add(Notif_Kosong);
        Notif_Kosong.setBounds(100, 475, 240, 20);

        Notif_Berhasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/master_berhasil.png"))); // NOI18N
        LoadingSplash.add(Notif_Berhasil);
        Notif_Berhasil.setBounds(82, 475, 268, 20);

        cbox.setBackground(new java.awt.Color(255, 255, 255));
        cbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbox.setForeground(new java.awt.Color(0, 0, 0));
        cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox.setBorder(null);
        cbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxMouseClicked(evt);
            }
        });
        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });
        LoadingSplash.add(cbox);
        cbox.setBounds(60, 235, 310, 35);

        kodePaket.setBackground(new java.awt.Color(255, 255, 255));
        kodePaket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kodePaket.setForeground(new java.awt.Color(0, 0, 0));
        kodePaket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoadingSplash.add(kodePaket);
        kodePaket.setBounds(60, 300, 310, 30);

        namaPaket.setBackground(new java.awt.Color(255, 255, 255));
        namaPaket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaPaket.setForeground(new java.awt.Color(0, 0, 0));
        namaPaket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoadingSplash.add(namaPaket);
        namaPaket.setBounds(60, 370, 310, 30);

        harga.setBackground(new java.awt.Color(255, 255, 255));
        harga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        harga.setForeground(new java.awt.Color(0, 0, 0));
        harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoadingSplash.add(harga);
        harga.setBounds(60, 440, 310, 30);

        HapusHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HapusHover.png"))); // NOI18N
        HapusHover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HapusHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HapusHoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HapusHoverMouseExited(evt);
            }
        });
        LoadingSplash.add(HapusHover);
        HapusHover.setBounds(40, 640, 353, 64);

        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hapus.png"))); // NOI18N
        Hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HapusMouseEntered(evt);
            }
        });
        LoadingSplash.add(Hapus);
        Hapus.setBounds(40, 640, 353, 64);

        UbahHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UbahHover.png"))); // NOI18N
        UbahHover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UbahHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UbahHoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UbahHoverMouseExited(evt);
            }
        });
        LoadingSplash.add(UbahHover);
        UbahHover.setBounds(40, 570, 353, 64);

        Ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ubah.png"))); // NOI18N
        Ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UbahMouseEntered(evt);
            }
        });
        LoadingSplash.add(Ubah);
        Ubah.setBounds(40, 570, 353, 64);

        TambahHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TambahHover.png"))); // NOI18N
        TambahHover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TambahHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TambahHoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TambahHoverMouseExited(evt);
            }
        });
        LoadingSplash.add(TambahHover);
        TambahHover.setBounds(40, 500, 353, 64);

        Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tambah.png"))); // NOI18N
        Tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TambahMouseEntered(evt);
            }
        });
        LoadingSplash.add(Tambah);
        Tambah.setBounds(40, 500, 353, 64);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoutButton.png"))); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
        });
        LoadingSplash.add(Logout);
        Logout.setBounds(300, 60, 114, 29);

        LogoutHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoutHover.png"))); // NOI18N
        LogoutHover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutHoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutHoverMouseExited(evt);
            }
        });
        LoadingSplash.add(LogoutHover);
        LogoutHover.setBounds(300, 60, 114, 29);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MasterPaketBG.png"))); // NOI18N
        LoadingSplash.add(Background);
        Background.setBounds(0, 0, 435, 844);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadingSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadingSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutHoverMouseClicked
        Login login;
        try {
            login = new Login();
            login.setVisible(true);
            login.pack();
            login.setLocationRelativeTo(null);
            login.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(UserPage3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LogoutHoverMouseClicked

    private void LogoutHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutHoverMouseExited
        LogoutHover.setVisible(false);
        Logout.setVisible(true);
    }//GEN-LAST:event_LogoutHoverMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        LogoutHover.setVisible(true);
        Logout.setVisible(false);
    }//GEN-LAST:event_LogoutMouseEntered

    private void cboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxMouseClicked

    }//GEN-LAST:event_cboxMouseClicked

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed

    }//GEN-LAST:event_cboxActionPerformed

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        try {
            setSelected();
        } catch (SQLException ex) {
            Logger.getLogger(UserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshMouseClicked

    private void TambahHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahHoverMouseClicked
        if (kodePaket.getText().equals("") || namaPaket.getText().equals("") || harga.getText().equals("")) {
            Notif_Ada.setVisible(false);
            Notif_Kosong.setVisible(true);
            Notif_Berhasil.setVisible(false);
        } else {
            try {
                
                sql = "INSERT INTO db_paket VALUES ('" + kodePaket.getText() + "','" + namaPaket.getText() + "','" + harga.getText().substring(4) + "')";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                Notif_Ada.setVisible(false);
                Notif_Kosong.setVisible(false);
                Notif_Berhasil.setVisible(true);
                initPaket();
            } catch (SQLException ex) {
                Notif_Ada.setVisible(true);
                Notif_Kosong.setVisible(false);
                Notif_Berhasil.setVisible(false);
            }

        }
    }//GEN-LAST:event_TambahHoverMouseClicked

    private void TambahHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahHoverMouseExited
        TambahHover.setVisible(false);
        Tambah.setVisible(true);
    }//GEN-LAST:event_TambahHoverMouseExited

    private void TambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahMouseEntered
        TambahHover.setVisible(true);
        Tambah.setVisible(false);
    }//GEN-LAST:event_TambahMouseEntered

    private void UbahHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UbahHoverMouseClicked
        if (kodePaket.getText().equals("") || namaPaket.getText().equals("") || harga.getText().equals("")) {
            Notif_Ada.setVisible(false);
            Notif_Kosong.setVisible(true);
            Notif_Berhasil.setVisible(false);
        } else {
            try {
                
                sql = "UPDATE db_paket SET KodePaket = '" + kodePaket.getText() + "', NamaPaket = '" + namaPaket.getText() + "', Harga = '" + harga.getText().substring(4) + "' WHERE db_paket.KodePaket = '" + cbox.getSelectedItem() + "'";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                Notif_Ada.setVisible(false);
                Notif_Kosong.setVisible(false);
                Notif_Berhasil.setVisible(true);
                initPaket();
            } catch (SQLException ex) {
                System.out.println(ex);
            }

        }
    }//GEN-LAST:event_UbahHoverMouseClicked

    private void UbahHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UbahHoverMouseExited
        UbahHover.setVisible(false);
        Ubah.setVisible(true);
    }//GEN-LAST:event_UbahHoverMouseExited

    private void UbahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UbahMouseEntered
        UbahHover.setVisible(true);
        Ubah.setVisible(false);
    }//GEN-LAST:event_UbahMouseEntered

    private void HapusHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusHoverMouseClicked
        if (kodePaket.getText().equals("") || namaPaket.getText().equals("") || harga.getText().equals("")) {
            Notif_Ada.setVisible(false);
            Notif_Kosong.setVisible(true);
            Notif_Berhasil.setVisible(false);
        } else {
            try {
                
                sql = "DELETE FROM db_paket WHERE KodePaket='" + cbox.getSelectedItem() + "'";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                Notif_Ada.setVisible(false);
                Notif_Kosong.setVisible(false);
                Notif_Berhasil.setVisible(true);
                initPaket();
            } catch (SQLException ex) {
                Notif_Ada.setVisible(true);
                Notif_Kosong.setVisible(false);
                Notif_Berhasil.setVisible(false);
            }

        }
    }//GEN-LAST:event_HapusHoverMouseClicked

    private void HapusHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusHoverMouseExited
        HapusHover.setVisible(false);
        Hapus.setVisible(true);
    }//GEN-LAST:event_HapusHoverMouseExited

    private void HapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusMouseEntered
        HapusHover.setVisible(true);
        Hapus.setVisible(false);
    }//GEN-LAST:event_HapusMouseEntered

    private void MiniButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniButtonMouseClicked
        this.setState(1);
    }//GEN-LAST:event_MiniButtonMouseClicked

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MasterPage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MasterPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JLabel Hapus;
    private javax.swing.JLabel HapusHover;
    private javax.swing.JPanel LoadingSplash;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel LogoutHover;
    private javax.swing.JLabel MiniButton;
    private javax.swing.JLabel Notif_Ada;
    private javax.swing.JLabel Notif_Berhasil;
    private javax.swing.JLabel Notif_Kosong;
    private javax.swing.JLabel Tambah;
    private javax.swing.JLabel TambahHover;
    private javax.swing.JLabel Ubah;
    private javax.swing.JLabel UbahHover;
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField kodePaket;
    private javax.swing.JTextField namaPaket;
    private javax.swing.JLabel refresh;
    // End of variables declaration//GEN-END:variables
}
