/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tripper;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form LoadingSplash
     *
     * @throws java.sql.SQLException
     */
    public NewUser() throws SQLException {
        initComponents();
        con = Tripper.getKoneksi();
        stat = con.createStatement();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 80, 80));

        Notif_Email.setVisible(false);
        Notif_Kosong.setVisible(false);
        Notif_Berhasil.setVisible(false);
    }

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LoadingSplash = new javax.swing.JPanel();
        Notif_Email = new javax.swing.JLabel();
        Notif_Kosong = new javax.swing.JLabel();
        Notif_Berhasil = new javax.swing.JLabel();
        ButtonHover = new javax.swing.JLabel();
        Button = new javax.swing.JLabel();
        RadioL = new javax.swing.JRadioButton();
        Email = new javax.swing.JTextField();
        RadioP = new javax.swing.JRadioButton();
        noHP = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        IsiBG = new javax.swing.JLabel();
        MiniButton = new javax.swing.JLabel();
        CloseButton = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 844));
        setUndecorated(true);

        LoadingSplash.setMaximumSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setMinimumSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setPreferredSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setLayout(null);

        Notif_Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bef_email.png"))); // NOI18N
        LoadingSplash.add(Notif_Email);
        Notif_Email.setBounds(120, 557, 194, 20);

        Notif_Kosong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bef_kosong.png"))); // NOI18N
        LoadingSplash.add(Notif_Kosong);
        Notif_Kosong.setBounds(122, 557, 192, 20);

        Notif_Berhasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bef_berhasil.png"))); // NOI18N
        LoadingSplash.add(Notif_Berhasil);
        Notif_Berhasil.setBounds(142, 557, 153, 16);

        ButtonHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IsiHover.png"))); // NOI18N
        ButtonHover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonHoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonHoverMouseExited(evt);
            }
        });
        LoadingSplash.add(ButtonHover);
        ButtonHover.setBounds(75, 582, 285, 51);

        Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IsiButton.png"))); // NOI18N
        Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMouseEntered(evt);
            }
        });
        LoadingSplash.add(Button);
        Button.setBounds(75, 582, 285, 51);

        RadioL.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RadioL);
        RadioL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RadioL.setForeground(new java.awt.Color(0, 0, 0));
        RadioL.setText("Laki-Laki");
        RadioL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoadingSplash.add(RadioL);
        RadioL.setBounds(90, 525, 99, 28);

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoadingSplash.add(Email);
        Email.setBounds(60, 460, 310, 30);

        RadioP.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RadioP);
        RadioP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RadioP.setForeground(new java.awt.Color(0, 0, 0));
        RadioP.setText("Perempuan");
        RadioP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoadingSplash.add(RadioP);
        RadioP.setBounds(220, 525, 122, 28);

        noHP.setBackground(new java.awt.Color(255, 255, 255));
        noHP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noHP.setForeground(new java.awt.Color(0, 0, 0));
        noHP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoadingSplash.add(noHP);
        noHP.setBounds(60, 390, 310, 30);

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 0, 0));
        nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoadingSplash.add(nama);
        nama.setBounds(60, 325, 310, 30);

        IsiBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IsiProfil.png"))); // NOI18N
        LoadingSplash.add(IsiBG);
        IsiBG.setBounds(35, 226, 365, 427);

        MiniButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MiniButton.png"))); // NOI18N
        MiniButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniButtonMouseClicked(evt);
            }
        });
        LoadingSplash.add(MiniButton);
        MiniButton.setBounds(340, 20, 33, 33);

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CloseButton.png"))); // NOI18N
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });
        LoadingSplash.add(CloseButton);
        CloseButton.setBounds(380, 20, 33, 33);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BeforeBG.png"))); // NOI18N
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundMouseClicked(evt);
            }
        });
        LoadingSplash.add(Background);
        Background.setBounds(0, 0, 435, 844);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadingSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadingSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiniButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniButtonMouseClicked
        this.setState(1);
    }//GEN-LAST:event_MiniButtonMouseClicked

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void BackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseClicked
        JOptionPane.showMessageDialog(null, "Anda belum mengisi biodata!");
    }//GEN-LAST:event_BackgroundMouseClicked

    private void ButtonHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHoverMouseClicked
        if (noHP.getText().equals("") || nama.getText().equals("") || Email.getText().equals("") || !(RadioL.isSelected() || RadioP.isSelected())) {
            Notif_Email.setVisible(false);
            Notif_Kosong.setVisible(true);
            Notif_Berhasil.setVisible(false);
        } else {
            try {
                String kel;
                if (RadioP.isSelected()) {
                    kel = "P";
                } else {
                    kel = "L";
                }
                sql = "INSERT INTO db_profil VALUES ('" + Tripper.getUsername() + "','" + nama.getText() + "','" + noHP.getText() + "','" + Email.getText() + "','" + kel + "')";
                java.sql.PreparedStatement pstAnjay2 = con.prepareStatement(sql);
                pstAnjay2.execute();

                String sqlAnjay = "UPDATE db_user SET role='user' WHERE Username = '" + Tripper.getUsername() + "'";
                java.sql.PreparedStatement pstAnjay3 = con.prepareStatement(sqlAnjay);
                pstAnjay3.execute();
                
                Notif_Email.setVisible(false);
                Notif_Kosong.setVisible(false);
                Notif_Berhasil.setVisible(true);

                UserPage lempar;
                try {
                    lempar = new UserPage();
                    lempar.setVisible(true);
                    lempar.pack();
                    lempar.setLocationRelativeTo(null);
                    lempar.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(UserPage3.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Notif_Email.setVisible(true);
                Notif_Kosong.setVisible(false);
                Notif_Berhasil.setVisible(false);
            }
        }
    }//GEN-LAST:event_ButtonHoverMouseClicked

    private void ButtonHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHoverMouseExited
        ButtonHover.setVisible(false);
        Button.setVisible(true);
    }//GEN-LAST:event_ButtonHoverMouseExited

    private void ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMouseEntered
        ButtonHover.setVisible(true);
        Button.setVisible(false);
    }//GEN-LAST:event_ButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewUser().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Button;
    private javax.swing.JLabel ButtonHover;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel IsiBG;
    private javax.swing.JPanel LoadingSplash;
    private javax.swing.JLabel MiniButton;
    private javax.swing.JLabel Notif_Berhasil;
    private javax.swing.JLabel Notif_Email;
    private javax.swing.JLabel Notif_Kosong;
    private javax.swing.JRadioButton RadioL;
    private javax.swing.JRadioButton RadioP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField noHP;
    // End of variables declaration//GEN-END:variables
}
