/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tripper;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Regis extends javax.swing.JFrame {

    /**
     * Creates new form LoadingSplash
     *
     * @throws java.sql.SQLException
     */
    public Regis() throws SQLException {
        initComponents();
        con = Tripper.getKoneksi();
        stat = con.createStatement();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 80, 80));

        ButtonHover.setVisible(false);
        Notif_Pakai.setVisible(false);
        Notif_Kosong.setVisible(false);
        Notif_Username.setVisible(false);
        Notif_Pass.setVisible(false);
        Notif_Berhasil.setVisible(false);
    }

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadingSplash = new javax.swing.JPanel();
        Password = new javax.swing.JPasswordField();
        Username = new javax.swing.JTextField();
        Notif_Berhasil = new javax.swing.JLabel();
        Notif_Username = new javax.swing.JLabel();
        Notif_Pass = new javax.swing.JLabel();
        Notif_Pakai = new javax.swing.JLabel();
        Notif_Kosong = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        ButtonHover = new javax.swing.JLabel();
        Button = new javax.swing.JLabel();
        MiniButton = new javax.swing.JLabel();
        CloseButton = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 844));
        setUndecorated(true);

        LoadingSplash.setMaximumSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setMinimumSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setPreferredSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setLayout(null);

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setBorder(null);
        LoadingSplash.add(Password);
        Password.setBounds(56, 630, 320, 40);

        Username.setBackground(new java.awt.Color(255, 255, 255));
        Username.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setBorder(null);
        LoadingSplash.add(Username);
        Username.setBounds(56, 524, 320, 40);

        Notif_Berhasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regis_Berhasil.png"))); // NOI18N
        LoadingSplash.add(Notif_Berhasil);
        Notif_Berhasil.setBounds(117, 690, 200, 16);

        Notif_Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regis_NotifUser.png"))); // NOI18N
        LoadingSplash.add(Notif_Username);
        Notif_Username.setBounds(45, 690, 344, 16);

        Notif_Pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regis_NotifPass.png"))); // NOI18N
        LoadingSplash.add(Notif_Pass);
        Notif_Pass.setBounds(23, 690, 388, 16);

        Notif_Pakai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regis_NotifPakai.png"))); // NOI18N
        LoadingSplash.add(Notif_Pakai);
        Notif_Pakai.setBounds(56, 690, 324, 20);

        Notif_Kosong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login_NotifKosong.png"))); // NOI18N
        LoadingSplash.add(Notif_Kosong);
        Notif_Kosong.setBounds(95, 690, 240, 20);

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Daftar_Login.png"))); // NOI18N
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        LoadingSplash.add(Login);
        Login.setBounds(318, 791, 52, 20);

        ButtonHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regis_ButtonHover.png"))); // NOI18N
        ButtonHover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonHoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonHoverMouseExited(evt);
            }
        });
        LoadingSplash.add(ButtonHover);
        ButtonHover.setBounds(40, 718, 353, 64);

        Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regis_Button.png"))); // NOI18N
        Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMouseEntered(evt);
            }
        });
        LoadingSplash.add(Button);
        Button.setBounds(40, 718, 353, 64);

        MiniButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MiniButton.png"))); // NOI18N
        MiniButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniButtonMouseClicked(evt);
            }
        });
        LoadingSplash.add(MiniButton);
        MiniButton.setBounds(340, 20, 33, 33);

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CloseButton.png"))); // NOI18N
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });
        LoadingSplash.add(CloseButton);
        CloseButton.setBounds(380, 20, 33, 33);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regis_Bg.png"))); // NOI18N
        LoadingSplash.add(Background);
        Background.setBounds(0, 0, 435, 844);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadingSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadingSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiniButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniButtonMouseClicked
        this.setState(1);
    }//GEN-LAST:event_MiniButtonMouseClicked

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMouseEntered
        ButtonHover.setVisible(true);
        Button.setVisible(false);
    }//GEN-LAST:event_ButtonMouseEntered

    private void ButtonHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHoverMouseExited
        ButtonHover.setVisible(false);
        Button.setVisible(true);
    }//GEN-LAST:event_ButtonHoverMouseExited

    private void ButtonHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHoverMouseClicked
        if (Username.getText().equals("") || Password.getText().equals("")) {
            Notif_Kosong.setVisible(true);
            Notif_Pakai.setVisible(false);
            Notif_Username.setVisible(false);
            Notif_Pass.setVisible(false);
        Notif_Berhasil.setVisible(false);
        } else if (Username.getText().length() < 4) {
            Notif_Kosong.setVisible(false);
            Notif_Pakai.setVisible(false);
            Notif_Username.setVisible(true);
            Notif_Pass.setVisible(false);
        Notif_Berhasil.setVisible(false);
        } else if (Password.getText().length() < 8 || Password.getText().length() > 16) {
            Notif_Kosong.setVisible(false);
            Notif_Pakai.setVisible(false);
            Notif_Username.setVisible(false);
            Notif_Pass.setVisible(true);
        Notif_Berhasil.setVisible(false);
        } else {
            try {
                sql = "SELECT * FROM db_user WHERE username='" + Username.getText() + "'";
                rs = stat.executeQuery(sql);

                if (rs.next()) {
                    Notif_Kosong.setVisible(false);
                    Notif_Pakai.setVisible(true);
                    Notif_Username.setVisible(false);
                    Notif_Pass.setVisible(false);
                    Notif_Berhasil.setVisible(false);
                } else {

                    sql = "INSERT INTO db_user VALUES ('" + Username.getText() + "','" + Password.getText() + "','newuser')";
                    java.sql.PreparedStatement pst = con.prepareStatement(sql);
                    pst.execute();
                    Notif_Kosong.setVisible(false);
                    Notif_Pakai.setVisible(false);
                    Notif_Username.setVisible(false);
                    Notif_Pass.setVisible(false);
                    Notif_Berhasil.setVisible(true);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Regis.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ButtonHoverMouseClicked

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        Login lempar;
        try {
            lempar = new Login();
            lempar.setVisible(true);
            lempar.pack();
            lempar.setLocationRelativeTo(null);
            lempar.setDefaultCloseOperation(Regis.EXIT_ON_CLOSE);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Regis.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Regis().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Regis.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Button;
    private javax.swing.JLabel ButtonHover;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JPanel LoadingSplash;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel MiniButton;
    private javax.swing.JLabel Notif_Berhasil;
    private javax.swing.JLabel Notif_Kosong;
    private javax.swing.JLabel Notif_Pakai;
    private javax.swing.JLabel Notif_Pass;
    private javax.swing.JLabel Notif_Username;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    // End of variables declaration//GEN-END:variables
}
