/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tripper;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class UserPage2 extends javax.swing.JFrame {

    /**
     * Creates new form LoadingSplash
     * @throws java.sql.SQLException
     */
    public UserPage2() throws SQLException {
        initComponents();
        con = Tripper.getKoneksi();
        stat = con.createStatement();
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 80, 80));
        
        LogoutHover.setVisible(false);
        Bt1Hover.setVisible(false);
        Bt3Hover.setVisible(false);
        
        setProfile();
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable2.setPreferredSize(null);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(125);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(225);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(145);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(45);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(145);
        loadData();
    }
    
    public void loadData() {
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        
        int totalRow = model.getRowCount();
        for (int i = totalRow - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        
        try {    
            rs = stat.executeQuery("SELECT Invoice, Username, NamaPelanggan, NamaPaket, Qty, TotalHarga FROM db_order, db_paket WHERE db_order.KodePaket = db_paket.KodePaket AND db_order.Username ='" + Tripper.getUsername() + "'");
            while (rs.next()) {
                Object[] obj = new Object[5];
                obj[0] = rs.getString("Invoice");
                obj[1] = rs.getString("NamaPelanggan");
                obj[2] = rs.getString("NamaPaket");
                obj[3] = rs.getString("Qty");
                obj[4] = "Rp. " + rs.getString("TotalHarga");
                model.addRow(obj);
            }
        } catch (SQLException e) {
            System.out.println("error SQLException : " + e.toString());
        }
    }

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    
    
    public void setProfile() throws SQLException {
        sql = "SELECT * FROM db_profil WHERE Username='" + Tripper.getUsername() + "'";
        rs = stat.executeQuery(sql);
        if (rs.next()) {
            Nama.setText(rs.getString("Nama"));
            if (rs.getString("JK").equals("L")) {
                male.setVisible(true);
                female.setVisible(false);
            } else if (rs.getString("JK").equals("P")) {
                male.setVisible(false);
                female.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadingSplash = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Nama = new javax.swing.JLabel();
        female = new javax.swing.JLabel();
        male = new javax.swing.JLabel();
        Bt3Hover = new javax.swing.JLabel();
        Bt3 = new javax.swing.JLabel();
        Bt1Hover = new javax.swing.JLabel();
        Bt1 = new javax.swing.JLabel();
        Bt2Hover = new javax.swing.JLabel();
        LogoutHover = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        MiniButton = new javax.swing.JLabel();
        CloseButton = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Bt1Hover1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 844));
        setUndecorated(true);

        LoadingSplash.setMaximumSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setMinimumSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setPreferredSize(new java.awt.Dimension(435, 844));
        LoadingSplash.setLayout(null);

        jTable2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Invoice", "Nama Pelanggan", "Nama Paket", "Qty", "Total Harga"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        LoadingSplash.add(jScrollPane2);
        jScrollPane2.setBounds(40, 230, 355, 403);

        Nama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nama.setForeground(new java.awt.Color(0, 0, 0));
        Nama.setText("a");
        LoadingSplash.add(Nama);
        Nama.setBounds(90, 100, 300, 32);

        female.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/female.png"))); // NOI18N
        LoadingSplash.add(female);
        female.setBounds(30, 70, 45, 61);

        male.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male.png"))); // NOI18N
        LoadingSplash.add(male);
        male.setBounds(30, 70, 45, 61);

        Bt3Hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg3Hover.png"))); // NOI18N
        Bt3Hover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt3Hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt3HoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt3HoverMouseExited(evt);
            }
        });
        LoadingSplash.add(Bt3Hover);
        Bt3Hover.setBounds(293, 720, 90, 90);

        Bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg3.png"))); // NOI18N
        Bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt3MouseEntered(evt);
            }
        });
        LoadingSplash.add(Bt3);
        Bt3.setBounds(293, 720, 90, 90);

        Bt1Hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg1Hover.png"))); // NOI18N
        Bt1Hover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt1Hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt1HoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt1HoverMouseExited(evt);
            }
        });
        LoadingSplash.add(Bt1Hover);
        Bt1Hover.setBounds(55, 720, 90, 90);

        Bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg1.png"))); // NOI18N
        Bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt1MouseEntered(evt);
            }
        });
        LoadingSplash.add(Bt1);
        Bt1.setBounds(55, 720, 90, 90);

        Bt2Hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg2Hover.png"))); // NOI18N
        Bt2Hover.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoadingSplash.add(Bt2Hover);
        Bt2Hover.setBounds(174, 720, 90, 90);

        LogoutHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoutHover.png"))); // NOI18N
        LogoutHover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutHover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutHoverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutHoverMouseExited(evt);
            }
        });
        LoadingSplash.add(LogoutHover);
        LogoutHover.setBounds(300, 60, 114, 29);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoutButton.png"))); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
        });
        LoadingSplash.add(Logout);
        Logout.setBounds(300, 60, 114, 29);

        MiniButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MiniButton.png"))); // NOI18N
        MiniButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniButtonMouseClicked(evt);
            }
        });
        LoadingSplash.add(MiniButton);
        MiniButton.setBounds(340, 20, 33, 33);

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CloseButton.png"))); // NOI18N
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });
        LoadingSplash.add(CloseButton);
        CloseButton.setBounds(380, 20, 33, 33);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu2BG.png"))); // NOI18N
        LoadingSplash.add(Background);
        Background.setBounds(0, 0, 435, 844);

        Bt1Hover1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bg1Hover.png"))); // NOI18N
        Bt1Hover1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoadingSplash.add(Bt1Hover1);
        Bt1Hover1.setBounds(55, 720, 90, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadingSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadingSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiniButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniButtonMouseClicked
        this.setState(1);
    }//GEN-LAST:event_MiniButtonMouseClicked

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        LogoutHover.setVisible(true);
        Logout.setVisible(false);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutHoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutHoverMouseExited
        LogoutHover.setVisible(false);
        Logout.setVisible(true);
    }//GEN-LAST:event_LogoutHoverMouseExited

    private void LogoutHoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutHoverMouseClicked
        Login login;
        try {
            login = new Login();
            login.setVisible(true);
            login.pack();
            login.setLocationRelativeTo(null);
            login.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(UserPage2.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_LogoutHoverMouseClicked

    private void Bt3HoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt3HoverMouseClicked
        UserPage3 lempar;
        try {
            lempar = new UserPage3();
            lempar.setVisible(true);
            lempar.pack();
            lempar.setLocationRelativeTo(null);
            lempar.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(UserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Bt3HoverMouseClicked

    private void Bt3HoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt3HoverMouseExited
        Bt3.setVisible(true);
        Bt3Hover.setVisible(false);
    }//GEN-LAST:event_Bt3HoverMouseExited

    private void Bt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt3MouseEntered
        Bt3.setVisible(false);
        Bt3Hover.setVisible(true);
    }//GEN-LAST:event_Bt3MouseEntered

    private void Bt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt1MouseEntered
        Bt1.setVisible(false);
        Bt1Hover.setVisible(true);
    }//GEN-LAST:event_Bt1MouseEntered

    private void Bt1HoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt1HoverMouseClicked
        UserPage lempar;
        try {
            lempar = new UserPage();
            lempar.setVisible(true);
            lempar.pack();
            lempar.setLocationRelativeTo(null);
            lempar.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(UserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Bt1HoverMouseClicked

    private void Bt1HoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt1HoverMouseExited
        Bt1.setVisible(true);
        Bt1Hover.setVisible(false);
    }//GEN-LAST:event_Bt1HoverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserPage2().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UserPage2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Bt1;
    private javax.swing.JLabel Bt1Hover;
    private javax.swing.JLabel Bt1Hover1;
    private javax.swing.JLabel Bt2Hover;
    private javax.swing.JLabel Bt3;
    private javax.swing.JLabel Bt3Hover;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JPanel LoadingSplash;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel LogoutHover;
    private javax.swing.JLabel MiniButton;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel female;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel male;
    // End of variables declaration//GEN-END:variables
}
